### ISSUE TITLE
Critical Bug - Not being able to switch to TMP Weapon after switchting to Secondary

### ISSUE THREAD

**Issue by arkprocession** [AoiKagase/Amxx-CrosshairMenu#5]
Hi

I just found out that if you pick up the TMP weapon with TT or CT, and then switch to a secondary weapon or other weapon like grenade or knife, you cannot switch back to TMP.

Only happens with that weapon so far.

Disabling this plugin fixes it, only if client restart the game. Otherwise he can even host a listenserver and the weapon won't work until next reboot of the game, given that he doesnt enter the server with the crosshair plugin.

Thank you

**Comment by AoiKagase** [comment]
I'm currently investigating, but we are experiencing problems with TMP not showing up in the slots even when this plugin is turned off.
It may be a bug in the ReGameDLL.

**Comment by arkprocession** [comment]
> I'm currently investigating, but we are experiencing problems with TMP not showing up in the slots even when this plugin is turned off. It may be a bug in the ReGameDLL.

Have you restarted the whole client after disabling plugin? in my case, the tmp fails until i do, don't know why.

If i enter the sv and leave, then host a listenserver, it still wont work after rebooting the whole game.

weird thing is i did not update regame in a while, and disabling the crosshair plugin and launching the game again to a listenserver makes the game works just fine.

**Comment by AoiKagase** [comment]
I was able to reproduce it.
However, the cause has not been elucidated. It will take some time.

**Comment by arkprocession** [comment]
> I was able to reproduce it. However, the cause has not been elucidated. It will take some time.

Working perfectly! Thank you, you marked it as a test, should we close it now?, what was the issue if you let me ask?

**Comment by AoiKagase** [comment]
I think it may be a bug that the CS client has internalized, but i have not been able to fully identify it.
Any modification using WeaponList messages will affect TMP.
(This has occurred with other plug-ins as well.)

This time, we used a tricky technique to initialize the WeaponList message when the TMP is equipped.
It may not be a good approach because it is symptomatic.

Note that this method still has the problem of the slot turning red when the BPAMMO is 0, even if there are bullets remaining in the magazine, but I do not believe there is any way to solve this problem.

**Comment by arkprocession** [comment]
that is enough for me :) thanks
